config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class="mb-5">All our flats(<%= @flats.size %>)</h1>
<div class="container d-flex flex-nowrap">
<% @flats.each do |flat| %>
<div class="flat-card">
  <h2><%= flat.name %></h2>
  <h4><%= flat.address %></h4>
  <div class="d-flex">
    <i class="small material-icons">person</i>
    <h4><%= flat.number_of_guests %></h4>
    <i class="small material-icons">attach_money</i>
    <h4><%= flat.price_per_night %></h4>
  </div>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAirbnb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="nav-bar d-flex justify-content-between align-items-center">
    <h3>Simple Airbnb</h3>
    <%= link_to "Add a flat", new_flat_path, class: "btn" %>
  </div>
  <%= yield %>
</body>
</html>